name: graphql_app
description: A new Flutter application with GraphQL.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_svg: ^0.21.0+1
  flutter_dotenv: ^3.1.0
  graphql: ^4.0.1
  json_annotation: 3.1.1
  intl: ^0.17.0


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: 1.11.5
  json_serializable: 3.5.1

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
   - assets/images/
   - .env

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
     - family: Metropolis Medium
       fonts:
         - asset: assets/fonts/Metropolis-Medium.otf
     - family: Metropolis Bold
       fonts:
         - asset: assets/fonts/Metropolis-Bold.otf
     - family: Metropolis Extra Bold
       fonts:
         - asset: assets/fonts/Metropolis-ExtraBold.otf
     - family: Metropolis Extra Bold Italic
       fonts:
         - asset: assets/fonts/Metropolis-ExtraBoldItalic.otf
     - family: Metropolis Bold Italic
       fonts:
         - asset: assets/fonts/Metropolis-BoldItalic.otf

  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
